### ISSUE TITLE
能增加图片收录吗？

### ISSUE THREAD

**Issue by donglin2000** [xiaoxinpro/xxjzWeb#1]
可以录入收据发票等数据。

**Comment by xiaoxinpro** [comment]
确实是个好提议，后续会考虑加进来。

**Comment by truongvinhba** [comment]
能不能做成无限分类

**Comment by xiaoxinpro** [comment]
@truongvinhba  你好，分类本身没有数量限制。另外不同问题请新建issues！

**Comment by xiaoxinpro** [comment]
从 [小歆记账正式版V2.1.0](https://github.com/xiaoxinpro/xxjzWeb/releases) 开始支持图片上传功能。
