### ISSUE TITLE
2.0的提示：请检测配置文件中的数据库主机地址、用户名和密码是否正确。

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#11]
所有目录都可以读写的了，系统安装时注册的管理员账号原来是admin吧，我曾经改过别的名字，现在改回admin还是不行

**Comment by xiaoxinpro** [comment]
`/Application/Common`目录是不是被你覆盖掉了，把原来的`/Application/Common`复制回来试试。

安装时会把配置文件写到`/Application/Common/Conf/config.php`文件中，所以升级时必需保留前版本的`/Application/Common`目录，否则升级程序读取不到你之前的数据库配置。

**Comment by wlzjd** [comment]
折腾过几次，原来的最初的找不到了，但升级时只复制了Home目录，Common没有动过，config.php文件还是旧的。

**Comment by wlzjd** [comment]
现在这个config.php在没把Home目录复制过去前是可以登陆的。

**Comment by xiaoxinpro** [comment]
那就检查一下`config.php`文件内数据库配置信息是否正确，再确认一下`updata_2.0.php`文件是否在项目根目录与读写权限。

**Comment by wlzjd** [comment]
config.php应该没错，原来是可以登陆的，目录都检查过了，都可以读写的。不知是不是我之前用phpmyadmin改过表: xxjz_user里的用户名有关，找不出原因哪就删掉旧数据库重装算了。

**Comment by xiaoxinpro** [comment]
你那个错误提示原因是 使用配置文件中的数据库配置连接不上数据库，若检查过配置没问题的话，把数据库和配置文件备份好，清空数据库安装一次试试看。

**Comment by wlzjd** [comment]
可以了，我把旧数据库删了重新导入最新的就可以用了，谢谢
