### ISSUE TITLE
老大，再给你提点建议，请考虑一下

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#12]
1.每一笔记录增加一个属性：比如说不同的帐户都有可能会有同一属性的钱进出，如某个小项目，但又区别于收入支出分类.
２.增加家庭成员帐户功能，家庭成员可以设置修改或查看权限。
３.增加一个汇总的界面，各个帐户的汇总金额，和每个月总的资金曲线，曲线可按金额显示或以百分比显示。
４.万位哪里增加一个“，”好看点。
谢谢你的软件，希望能采纳。

**Comment by wlzjd** [comment]
看到你的回复很高兴，我觉得可以把问题１和建议放在一起来考虑，你看一下这样是否可行
问题1：目前的资金账户机制有一个尚未解决的麻烦，资金账户间的资金流动问题，目前还未找到可以在不影响记账与统计功能下实现。
给记录一个类拟帐户这样可选的属性或标签，有一个“默认”或“个人”字样的默认选项，也有“转帐”或“调拔”这个选项，当选项是“转帐”时，该记录不参与统计，这个属性也可以自行添加“公司”，“家庭”，等标签，同时，在查询里和统计里也可以有这个属性的统计，这样就能统计“公司”，“家庭”或“个人”名下的收支情况，备注里也能实现，就是便捷性差点。
我现在的处理方式是转帐时，我就在不同的帐户里各增加一条记录，一进一出，唯一不好的是收支变大了，感觉好有钱一样，呵呵。

**Comment by xiaoxinpro** [comment]
这样会使数据结构太混乱，使用上也是一头雾水了，重点还是要简单，不能再增加使用难度了。
