### ISSUE TITLE
自动安装的数据库表account_funds多了一个account_funds

### ISSUE THREAD

**Issue by killua0083** [xiaoxinpro/xxjzWeb#13]
自动安装的数据库表account_funds多了一个account_funds，导致建立新的资金账户报错
`
1364:Field 'fundstype' doesn't have a default value [ SQL语句 ] : INSERT INTO `xxjz_account_funds` (`fundsname`) VALUES ('test')
`

**Comment by killua0083** [comment]
xxjz_account_funds 中的 ufid  字段也是这个问题，缺少default value

**Comment by killua0083** [comment]
还有在xxjz.sql文件中，`xxjz_account_funds`建立的字段是uid，应该是ufid吧
`
DROP TABLE IF EXISTS `xxjz_account_funds`;
CREATE TABLE `xxjz_account_funds` (
  `fundsid` int(11) NOT NULL AUTO_INCREMENT,
  `fundsname` varchar(24) NOT NULL,
  `uid` int(11) NOT NULL,
  PRIMARY KEY (`fundsid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
`

**Comment by xiaoxinpro** [comment]
不是很清楚你要表达的内容，你是全新安装出的问题吗？

建议以下解决方案：

请确保你的数据库中“xxjz_”开头的表都已经删除，然后删除根目录下的“install.tmp”，最后访问根目录下的“install.php”根据提示填写信息点击安装就可以了。

**Comment by xiaoxinpro** [comment]
xxjz.sql文件 和 install.tmp文件 确实有问题，感谢提交BUG。

**Comment by killua0083** [comment]
对了  还有一个问题请教一下   为什么不设置账户的初始金额？

**Comment by xiaoxinpro** [comment]
没有必要设置初始金额吧，自己添加一个收入就好了吧。
