### ISSUE TITLE
编辑详细账目时出现404

### ISSUE THREAD

**Issue by oniyakun** [xiaoxinpro/xxjzWeb#15]
如图，重新安装后还是一样
![image](https://user-images.githubusercontent.com/30280837/54730217-a249e080-4bc2-11e9-9180-53f10f22d19b.png)

**Comment by xiaoxinpro** [comment]
请参照#16安装最新版本https://github.com/xiaoxinpro/xxjzWeb/releases/tag/V2.0.2
