### ISSUE TITLE
2.X编辑账目时出现错误

### ISSUE THREAD

**Issue by tubuxing** [xiaoxinpro/xxjzWeb#16]
![2019-05-02_165008](https://user-images.githubusercontent.com/50197602/57065004-a2c5b300-6cfa-11e9-932f-8bf8515fec58.png)

**Comment by xiaoxinpro** [comment]
你编辑了什么内容，我这边无法复现你这个错误。

**Comment by tubuxing** [comment]
> 你编辑了什么内容，我这边无法复现你这个错误。
就是查询和主页上编辑记账明细（二级目录，群晖搭建的）tubuxing.xicp.net:40543/leejz   账号 admin 密码admin123
![2019-05-02_210207](https://user-images.githubusercontent.com/50197602/57077044-9e5ec180-6d1d-11e9-99a7-bce93915465c.png)

**Comment by xiaoxinpro** [comment]
你这个网址打不开，你看一下试一下在我的网站上面会不会出现这个错误，另外你把完整的错误信息复制过来，不要截图。
```
http://jz.xxgzs.org/xxjzApp/index.php
Demo账号：demo
Demo密码：xxgzs.org
```

**Comment by tubuxing** [comment]
:(

Too few arguments to function ArrDataToShowData(), 2 passed in /volume1/web/leejz/Application/Home/Controller/EditController.class.php on line 43 and exactly 3 expected
错误位置

FILE: /volume1/web/leejz/Application/Home/Common/function.php 　LINE: 466

TRACE

#0 /volume1/web/leejz/Application/Home/Controller/EditController.class.php(43): ArrDataToShowData(Array, Array)
#1 [internal function]: Home\Controller\EditController->index()
#2 /volume1/web/leejz/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\EditController))
#3 /volume1/web/leejz/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Home\Controller\EditController), 'index')
#4 /volume1/web/leejz/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#5 /volume1/web/leejz/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#6 /volume1/web/leejz/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#7 /volume1/web/leejz/index.php(24): require('/volume1/web/le...')
#8 {main}

ThinkPHP<http://www.thinkphp.cn/>3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chishin <notifications@github.com>
发送时间: Thursday, May 2, 2019 9:16:08 PM
收件人: xiaoxinpro/xxjzWeb
抄送: tubuxing; Author
主题: Re: [xiaoxinpro/xxjzWeb] 2.X编辑账目时出现错误 (#16)


你这个网址打不开，你看一下试一下在我的网站上面会不会出现这个错误，另外你把完整的错误信息复制过来，不要截图。

http://jz.xxgzs.org/xxjzApp/index.php

Demo账号：demo

Demo密码：xxgzs.org



―

**Comment by tubuxing** [comment]
> 你这个网址打不开，你看一下试一下在我的网站上面会不会出现这个错误，另外你把完整的错误信息复制过来，不要截图。
> 
> ```
> http://jz.xxgzs.org/xxjzApp/index.php
> Demo账号：demo
> Demo密码：xxgzs.org
> ```

不会出现错误，我看了一下网址构成  多了一个  ?s=

**Comment by xiaoxinpro** [comment]
你替换一下[/Application/Home/Common/function.php](https://github.com/xiaoxinpro/xxjzWeb/blob/master/Application/Home/Common/function.php)这个文件。
然后删除你`/volume1/web/leejz/Application/Runtime/`目录下全部文件。
再试一下。

**Comment by tubuxing** [comment]
替换这个文件就可以了呢，，Application/Home/Common/function.php，感谢大神
