### ISSUE TITLE
http://jz.xxgzs.org/xxjzApp/index.php: 404

### ISSUE THREAD

**Issue by jonahfang** [xiaoxinpro/xxjzWeb#17]
访问不到这个网址!

**Comment by jonahfang** [comment]
https://jz.xiaoxin.pro/xxjzApp/index.php?s=/Home/Login/index.html ?

**Comment by wlzjd** [comment]
备注字段能不能放长点，64个字符太少了

**Comment by xiaoxinpro** [comment]
@jonahfang 抱歉，由于`jz.xxgzs.org`备案问题，域名改到`jz.xiaoxin.pro`。
