### ISSUE TITLE
nignx下如何配置

### ISSUE THREAD

**Issue by wxf26054** [xiaoxinpro/xxjzWeb#18]

**Comment by wxf26054** [comment]
nginx下部署后出现404，该怎样解决

**Comment by xiaoxinpro** [comment]
不需要额外配置，显示404是不是你的PHP没有开启错误信息显示，或者参考环境要求:
https://www.kancloud.cn/manual/thinkphp/1681
希望可以帮助到你！

**Comment by wxf26054** [comment]
还是提示404 Not Found

**Comment by KYatoo** [comment]
Warning: fopen(./Application/Common/Conf/config.php): failed to open stream: Permission denied in install.php on line 369
Unable to open file!
提示没有权限请问我该给什么权限啊？

**Comment by xiaoxinpro** [comment]
@KYatoo 需要有读写权限，你可以直接写成777权限！

**Comment by KYatoo** [comment]
感

> @KYatoo 需要有读写权限，你可以直接写成777权限！

感谢，我查看了下 改成666正常了

**Comment by KYatoo** [comment]
难过的是我现在配置完成到登陆界面又出现了新的问题。系统发生错误，更难过的是，本菜鸡看不懂。

**Comment by xiaoxinpro** [comment]
> 难过的是我现在配置完成到登陆界面又出现了新的问题。系统发生错误，更难过的是，本菜鸡看不懂。

提示什么错误，你截图我看一下吧

**Comment by KYatoo** [comment]
啊啊啊 我忘了截图。大概也是write_error之类的。一怒之下，将整个文件夹777了。遂正常。不过我还是奇怪，我看了出问题的几个php都是664权限，只对其他用户做的限制。不知道我哪里没操作对。

**Comment by KYatoo** [comment]
提示的错误就是没有写权限，但我看他提示出问题的文件都是664，总之有点奇怪。改成777虽然解决了感觉安全性上大打折扣，不知道正确的操作应该怎样。

**Comment by xiaoxinpro** [comment]
> 提示的错误就是没有写权限，但我看他提示出问题的文件都是664，总之有点奇怪。改成777虽然解决了感觉安全性上大打折扣，不知道正确的操作应该怎样。

你权限666程序没有写入权限，肯定不行啊，没什么好担心安全问题的。
