### ISSUE TITLE
2.0.2版本 nginx下访问失败

### ISSUE THREAD

**Issue by mrli20182018** [xiaoxinpro/xxjzWeb#19]
![image](https://user-images.githubusercontent.com/42336683/66562976-57f47500-eb8f-11e9-8dad-ff17e0ba6cc4.png)
访问的时候 跳转到这个地址 然后就404了 
http://192.168.89.19:8100/index.php/Home/Login/index.html

**Comment by xiaoxinpro** [comment]
请尝试开启PHP错误提示，应该是运行时出错导致的404。




| |
小歆
邮箱：zhangzejin3883@163.com
|

签名由 网易邮箱大师 定制

在2019年10月10日 18:55，mrli20182018 写道：


访问的时候 跳转到这个地址 然后就404了
http://192.168.89.19:8100/index.php/Home/Login/index.html

**Comment by mrli20182018** [comment]
调试模式打开了 php-fpm没有错误日志 nginx也看不到有用的错误信息

**Comment by xiaoxinpro** [comment]
你看一下根目录下的Application文件夹及其子文件的权限是不是755。

**Comment by mrli20182018** [comment]
![image](https://user-images.githubusercontent.com/42336683/66618455-b8c19300-ec0b-11e9-9e87-29417c907e1b.png)
要手动修改一个 / 为?s=

**Comment by mrli20182018** [comment]
请问你的是什么环境 每个页面都这样 Home前面的变成 / 手动修改 ?s= 就可以访问 

我环境为centos6.8 php5.3.3 nginx 1.14.2

**Comment by xiaoxinpro** [comment]
我也发现了这个问题，配置文件缺少一条配置。
`/Application/Common/Conf/config.php` 文件内在第18行添加 `'URL_MODEL'  => 3,` 即可解决问题。

**Comment by mrli20182018** [comment]
这个问题 我使用nginx的url重写也解决了
rewrite /index.php/(.*) /index.php?s=$1;
登录的时候 我有遇到了问题
测试了创建账号没问题 数据库里有账号 邮件重置密码 也没问题
登录的时候 报错如下
![image](https://user-images.githubusercontent.com/42336683/66619852-fbd23500-ec10-11e9-92ee-016e3f0bfce5.png)

**Comment by xiaoxinpro** [comment]
检查一下你的session是不是没有开启

**Comment by mrli20182018** [comment]
解决了 根据报错 创建了一个 session目录 授权给php用户就可以了
