### ISSUE TITLE
什么时候才能实现帐户内互转而不纳入统计呀，这样用信用卡和管理都不方便

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#21]

**Comment by xiaoxinpro** [comment]
该功能后续会增加的，目前正在重构数据安装与升级代码，为了方便后续数据库结构灵活变更。

**Comment by wlzjd** [comment]
建议在记帐界面下，在“收入”，“支出”的旁边增加多一个“转帐”的选项，录入界面就跟收支一样，只是金额不纳入收支的统计范围，这样应该容易实现些。

**Comment by xiaoxinpro** [comment]
已经在做了，请稍安勿躁，因为涉及重大数据变动，需要进行一系列测试才会发布。

**Comment by wlzjd** [comment]
好的，现在好期待。

**Comment by wlzjd** [comment]
已经下载最新版使用了，目前最好用的手机WEB记帐，没有之一。
感谢你的贡献
