### ISSUE TITLE
服务端版本过低 检测到 https://jz.xiaoxin.pro/xxjzApp 服务器版本过低，请安装最新版本小歆记账。

### ISSUE THREAD

**Issue by lk1988900** [xiaoxinpro/xxjzWeb#23]
服务端版本过低 检测到 https://jz.xiaoxin.pro/xxjzApp 服务器版本过低，请安装最新版本小歆记账。
老大，这是什么问题呢？我在使用你的小程序项目学习，谢谢

**Comment by xiaoxinpro** [comment]
这个应该是微信小程序提示的错误，但是Issue你发到服务端项目来了；问题总的来说就是提示上面写得，具体一下三点：

1、你没有下载[Releases](https://github.com/xiaoxinpro/xxjzWeChat/releases)版本的微信小程序，开发版本需要对应开发版本的服务端，所以提示版本过低。（README文件已经说明过了，建议使用Releases版本，开发版本可能有较多的问题）

2、你没有搭建自己的服务端，你同样需要下载[Releases](https://github.com/xiaoxinpro/xxjzWeb/releases)版本的服务端并部署。

3、以上结束后在小程序根目录下的/app.js文件中，配置相应的服务端接口。

**Comment by lk1988900** [comment]
实在不好意思，第一次弄这个，有些不太懂，感谢
