### ISSUE TITLE
能请作者尽快完善信用卡这一块吧！这一年下来的帐目数据因为没有转帐这一块功能，统计出来的数目相差很大呀

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#24]
没有转帐的功能，正常支出和还信用卡的统计在一块了，造成收入和支出都失真了，都反映不出这一年来的真实收支情况，能请你尽快一些吗，再完善一下就完美了。
另外，请在每次更新时提供一个手动更新数据库的脚本，因为在群晖里按教程更新好像更新不了，把新数据库导进去后旧数据全没了 －＿－　　 
这个软件还是不错的，有了这个都没必要用随手记哪些第三方的平台了，期待你加快加快再加快，要不然记录下来的收支真的没有参考性。

**Comment by xiaoxinpro** [comment]
已经在做了，请稍安勿躁，因为涉及重大数据变动，需要谨慎操作！
Duplicate of #21
