### ISSUE TITLE
自己的服务器上怎么关闭广告，然后开放功能，因为就自己跟老婆用~！

### ISSUE THREAD

**Issue by oemsys** [xiaoxinpro/xxjzWeb#29]
自己的服务器上怎么关闭广告，然后开放功能，因为就自己跟老婆用~！
图片可以设置多几张吗？

**Comment by xiaoxinpro** [comment]
1、服务端没有广告
2、服务端最多可以设置9张图片上传，可以修改`/Application/Home/Conf/config.php `文件中的`IMAGE_COUNT`配置项。

**Comment by oemsys** [comment]
![image](https://user-images.githubusercontent.com/32034317/83216545-1bb46a00-a19c-11ea-81c9-fb5a728d18e3.png)

**Comment by xiaoxinpro** [comment]
此项目是服务端项目，你这个截图是微信小程序项目
https://github.com/xiaoxinpro/xxjzWeChat
