### ISSUE TITLE
CONFIG

### ISSUE THREAD

**Issue by 940520** [xiaoxinpro/xxjzWeb#3]
安装的时候貌似无法写入config，查看SQL已经写入，配置信息未写入config.php，手动配置config文件后正常使用。错误信息忘记了。没有再折腾。

**Comment by 940520** [comment]
PHP:5.5.38
Microsoft-IIS/8.5
Windows Server 2012 R2 Datacenter Edition AMD64

**Comment by xiaoxinpro** [comment]
会不会是你的config.php文件没有读写权限
