### ISSUE TITLE
希望有API开放出来？

### ISSUE THREAD

**Issue by oemsys** [xiaoxinpro/xxjzWeb#30]
发现直接数据库新增数据刷新不出来，需在网页或微信中新增一条收入支出才会把手动写到数据库的记录刷新出来。有API就不需要这么烦了~！

**Comment by xiaoxinpro** [comment]
1、直接操作数据库是因为缓存没有更新。
2、API本身就有，由于还在频繁更新中所以目前还不会出文档，你可以自己看API代码。
