### ISSUE TITLE
谢谢，已经用上最新版了，请教下怎修改备注字段的文字长度限制？

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#31]

**Comment by xiaoxinpro** [comment]
修改 `xxjzWeb/Application/Home/Conf/config.php` 配置文件，更改备注长度限制。

**Comment by wlzjd** [comment]
64有点小，最大能改为128吗？

**Comment by xiaoxinpro** [comment]
改数据库`xxjz_account`表中的`acremark`字段，然后同步改上面的配置文件。
