### ISSUE TITLE
当添加转帐记录后，主页界面下的下拉页数和“下一页”里均不能显示早期的记帐记录.请检查一下。

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#32]
当添加多笔转帐记录后，主页界面下的下拉页数和“下一页”里均不能显示早期的收支记帐记录，但在查询里在备注里输入关键字则可以查到相关记录，如果备注空白，帐户、分类、时间等不管有否选择，都查不到早前的一些记录。

**Comment by xiaoxinpro** [comment]
经测试没有发现上述问题，请检查安装版本是否为最新，或提供测试账号发送到pro@xxgzs.org邮箱。

**Comment by wlzjd** [comment]
是最新的版本，昨晚删掉重新下载了。没弄外网透传，一直在内网用。
原来的记录中显示的是到5月28号的，我试着删除了2条记录，发现原来按不能显示的2条历史记录可以显示了，这2条记录是5月26，27号的，我继续删除，发现原来只能显示最近的4页记录，后面的就不能显示了。你看看能不能找到原因，不行我开外网访问给你检查了。

**Comment by xiaoxinpro** [comment]
我测试下来是没有问题的，你可以尝试删除 `./Application/Runtime/` 目录下全部文件再试一下。

**Comment by wlzjd** [comment]
删除了不行，我发帐号到你邮箱了

**Comment by xiaoxinpro** [comment]
该问题已修复，安装最新版本再试一下。
