### ISSUE TITLE
转帐界面存在着帐户数量显示不完整

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#33]
转出账户最多只显示9个帐户，默认帐户不显示，转入帐户最多只显示7个，默认帐户也不显示。
建议可以上下滚动显示更多帐户，同时默认帐户也可以参与转帐。

**Comment by xiaoxinpro** [comment]
默认账户是不显示的，因为本身是不存在数据库中的，后续将删除默认账户功能。
> 目前老用户可手动删除默认账户
账户过多会导致UI遮挡，后续会调整UI。

**Comment by wlzjd** [comment]
现在转帐使用没用问题了。另外觉得如果取消默认帐户可能不太方便，因为平时默认帐户都是当作现金或微信等常用支出帐户，如果删除把记录转到别的帐户上去，每次登记都要下拉重选一次帐户，而且因为帐户名不能排序，日常很多支出反而多了一个选择常用帐户的过程。

**Comment by wlzjd** [comment]
另外又发现一个情况，在查询里选择分类里不管是选择支出或收入里的分类大类或小类，都会把转帐记录查询出来。又得麻烦你了

**Comment by xiaoxinpro** [comment]
该问题已修复，安装最新版本再试一下。
