### ISSUE TITLE
使用中发现帐户排序没有问题，分类排序保存无效

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#34]
最新版，帐户是有排序按钮这个选项再保存的，分类没有，但保存后刷新还是原来的顺序，是我数据库没更新好吗？

**Comment by xiaoxinpro** [comment]
实测并没有发现该问题，你可以尝试删除 `./Application/Runtime/` 目录下全部文件再试一下。

数据库更新需要替换根目录下的`updata.php`和`sql.php`文件，然后浏览器访问`updata.php`按照流程更新数据库即可。

**Comment by xiaoxinpro** [comment]
另外还建议清除浏览器缓存，因为项目静态JS文件有调整。

![清除浏览器缓存](https://user-images.githubusercontent.com/11443745/87260893-abad3980-c4e6-11ea-867a-367fb630f885.png)

**Comment by wlzjd** [comment]
我重新升级了一下，还是不能保存。我检查了一下表: xxjz_account_class，发现SORT字段在保存排序时地整体变化，如保存收入分类的排序时，所有的值为变成7，当修改支出分类排序保存时，所有值为变成29，手动修改表: xxjz_account_class排序，但点保存后还是会改为7或29。这个7和29应该是支出和收入分类的总数。

**Comment by xiaoxinpro** [comment]
重新更新一下项目文件吧，我无论是从升级通道还是全新安装都没有复现你的问题。

**Comment by wlzjd** [comment]
今天更新最新的正常了
