### ISSUE TITLE
查询里的支出分类是没有经过排序的

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#35]

**Comment by xiaoxinpro** [comment]
记账是根据记账时间顺序排序的，与分类排序无关。

**Comment by wlzjd** [comment]
是在“查询|里“查询账目”界面下查询明细时，查询的分类选择里的分类还是旧版排列，哪记帐界面下的分类排序是不一样的，不是说查询结果排序，是查询条件选择的排序。
