### ISSUE TITLE
查询里可以统计收入和支出金额，但是不能统计转帐金额。

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#36]

**Comment by xiaoxinpro** [comment]
转帐属于内部账户间资金变动，统计并没有任何意义，针对账户金额统计可以查看资金账户界面的账户金额。

**Comment by wlzjd** [comment]
转帐统计有些时候还是有点用的，比如记录报销这种类型消费的时候，如果把需报销的费用列为支出，把报销所得列为收入，这样有时会出现一段时间收支明显变大了，实际上你的收入并没有真的增加，报销所得的钱是你前期采购的钱或是机票车费等支出，这些费用适合用一个报销帐户来记录，发样消费就转入，报销后就转出，就样就不会统计失真，也容易统计报销费用。
