### ISSUE TITLE
能否加入账单数据导出导入

### ISSUE THREAD

**Issue by xiebic** [xiaoxinpro/xxjzWeb#43]
能否加入账单数据导出导入功能，有时候换服务器有点麻烦

**Comment by xiaoxinpro** [comment]
直接到数据库中将全部表导出，再到新服务器中将全部表导入即可。

该功能不属于记账软件的必要功能，考虑到数据安全不会增加此功能。

**Comment by xiebic** [comment]
好的，谢谢
