### ISSUE TITLE
很感谢您的软件，请问能增加现金，银行卡，债务等分类选择和提供数据库导入吗？

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#7]
另我在群晖中安装不了，不知是不是数据库的问题，所以请提供一下数据库导入试一下。

**Comment by xiaoxinpro** [comment]
1、分类可以在“分类管理中自由添加”`域名/index.php?s=/Home/Class/index`
2、安装过程出现了什么错误提示可以发出吗？ 是否是确实文件目录的读写权限问题。
3、数据库可以发出来，但是相关配置信息需要额外手动修改。

**Comment by xiaoxinpro** [comment]
4、数据库文件请查看`https://github.com/xiaoxinpro/xxjzWeb/blob/master/xxjz.sql`
5、请手动配 `根目录/Application/Common/Conf/config.php` 文件

**Comment by wlzjd** [comment]
您回复得真快，现在可以显示登陆界面了，可是登陆过后显示
:(

Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'
错误位置
FILE: /volume1/web/jzWeb/ThinkPHP/Library/Think/Db/Driver/Mysql.class.php 　LINE: 36

ThinkPHP3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]

系统环境：apache 2.4+php5.6

系统环境：apache 2.4+php7.0则会出现下面的错误：
:(

Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'
错误位置
FILE: /volume1/web/jzWeb/ThinkPHP/Library/Think/Db/Driver/Mysql.class.php 　LINE: 36

TRACE
#0 /volume1/web/jzWeb/ThinkPHP/Library/Think/Db/Driver.class.php(97): Think\Db\Driver\Mysql->parseDsn(Array)
#1 /volume1/web/jzWeb/ThinkPHP/Library/Think/Db/Driver.class.php(1075): Think\Db\Driver->connect()
#2 /volume1/web/jzWeb/ThinkPHP/Library/Think/Db/Driver/Mysql.class.php(47): Think\Db\Driver->initConnect(true)
#3 /volume1/web/jzWeb/ThinkPHP/Library/Think/Model.class.php(134): Think\Db\Driver\Mysql->getFields('xxjz_user')
#4 /volume1/web/jzWeb/ThinkPHP/Library/Think/Model.class.php(122): Think\Model->flush()
#5 /volume1/web/jzWeb/ThinkPHP/Library/Think/Model.class.php(1454): Think\Model->_checkTableInfo()
#6 /volume1/web/jzWeb/ThinkPHP/Library/Think/Model.class.php(97): Think\Model->db(0, '', true)
#7 /volume1/web/jzWeb/ThinkPHP/Common/functions.php(621): Think\Model->__construct('user', '', '')
#8 /volume1/web/jzWeb/Application/Home/Common/function.php(32): M('user')
#9 /volume1/web/jzWeb/Application/Home/Controller/LoginController.class.php(11): UserLogin('admin', 'admin888')
#10 [internal function]: Home\Controller\LoginController->index()
#11 /volume1/web/jzWeb/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Home\Controller\LoginController))
#12 /volume1/web/jzWeb/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Home\Controller\LoginController), 'index')
#13 /volume1/web/jzWeb/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#14 /volume1/web/jzWeb/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#15 /volume1/web/jzWeb/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#16 /volume1/web/jzWeb/index.php(24): require('/volume1/web/jz...')
#17 {main}

**Comment by xiaoxinpro** [comment]
`MYSQL_ATTR_INIT_COMMAND`是你的PHP环境没有配置好MYSQL，请自行谷歌吧。

**Comment by wlzjd** [comment]
群晖就是折腾，已经可以用了。我说的分类其实是资金帐户的分类，是在收入支出的分类之外再增加一个分类，这样好单独登记各个帐户的收支，债务帐户和其它帐户的关系是转帐关系，希望你能增加。
