### ISSUE TITLE
你好，使用时发现没有资金帐户分类真的很不方便，请问可以再增加一个自定义分类吗？

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#8]

**Comment by xiaoxinpro** [comment]
你提到的这个功能我会认真考虑的。
如果增加这个功能，数据库结构上面会有较大调整，对于已安装的人来说升级会带来数据丢失的风险。

**Comment by wlzjd** [comment]
谢谢你的重视，如果可以的话，我愿第一个测试。不想用其它软件是因为数据是放在别人哪的，人穷，不想给别人看穿…………哈哈
