### ISSUE TITLE
你好，我发现查询的界面里分类哪一列是空白的，是BUG还是我安装不完整引起的？

### ISSUE THREAD

**Issue by wlzjd** [xiaoxinpro/xxjzWeb#9]

**Comment by wlzjd** [comment]
我看了一下Demo里是有的，但我的主页下面和查询里都没有，不知道是不是用户权限的问题，但能自已增加和选择分类，查询里也能按分类查询，就是在主页和查询的结果里没有分类

**Comment by xiaoxinpro** [comment]
有什么错误提示吗？你这样描述我也没办法定位问题。

**Comment by xiaoxinpro** [comment]
你安装的master分支吧，目前master分支还在测试，实际请使用releases版本。

https://github.com/xiaoxinpro/xxjzWeb/releases

**Comment by wlzjd** [comment]
重新下载releases版本了，所有功能正常，期待V2.
